name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Test
        env:
          WEBSIDE: ${{ secrets.TEST_WEBSITE }}
          LOGIN: ${{ secrets.TEST_LOGIN }}
          PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: run npm test